### ISSUE TITLE
pip installs in place of apt repo

### ISSUE THREAD

**Issue by RogueM** [pimoroni/get#15]
I noticed that you are sometimes installing python modules that are widely available in the Raspbian repo, things like rpi.gpio to name but one.

Wouldn't it be sensible, perhaps to attempt to install those things using Apt where possible, so they are kept up-to-date when users are running apt-get upgrade? or is that purposely so so they stay in sync with your libs?

**Comment by RogueM** [comment]
@Gadgetoid - I have been investigating my recent issues with python requiring sudo to run to access gpio (as discussed on Monday) and I have narrowed it down to the version of rpi.gpio on the pip repo (version 0.5.11).

It interferes quite badly with the newer version available on the apt repo at this point (version 0.6.0a3). If rip.gpio is installed from pip first then elevated privileges with be required, even if the version on apt is then rolled on (pip list will still mention 0.5.11 as the active version). removing the pip version manually will allow version 0.6.0 to kick in and from then on sudo won't be required.

so, yes, I think the scripts in this repo have to attempt to install rip.gpio from apt, as opposed to let the pip version being rolled out as a requirement as specified in the setup.py of the different products. This way, when the one-line installers are used then we will avoid the problem.

... of course there could be any number of other python libs out there that could pull rpi.gpio from pip before Pimoroni installers are used, but at least they will no longer trigger the issue.

Ultimately, ideally, the rip.gpio version in the pip repo should be upgraded, but I do not know where to make the request, and perhaps whoever is responsible may have a good reason to lag behind? what's your thought on the matter, where should we flag the concern?

**Comment by RogueM** [comment]
... python(3)-rpi.gpio will be added to the pkgdeplist where appropriate. No attempt will be made to remove the pip version.

**Comment by lurch** [comment]
Not that it matters now, but....

> Ultimately, ideally, the rip.gpio version in the pip repo should be upgraded

Version of [rpi.gpio in the pip repo](https://pypi.python.org/pypi/RPi.GPIO) is now up to date again (currently 0.6.2).

> but I do not know where to make the request

https://sourceforge.net/p/raspberry-gpio-python/tickets/ would have been the correct place to ask.

**Comment by RogueM** [comment]
cheers Andrew, yes, Ben pitched in back then and clarified how he sees the different channels and what to expect from them. I think even Jessie lite is shipping with rpi.gpio pre-installed at this point, so it should seldom catch users off-guard.

Good to know a sudoless version is now gracing pip though as I'm about (in a few weeks time) to evaluate feasability to officially support Ubuntu MATE and no doubt this would have been a (slightly) sticky point with the pip repo lagging behind.
