### ISSUE TITLE
improve handling of user input (confirmation) for 'stuck keys'

### ISSUE THREAD

**Issue by RogueM** [pimoroni/get#188]
currently, any repeat of 'y' is treated as opting out of validation/confirmation. The confirm() function should be less sensitive to avoid key repeat due to malfunctioning keyboard, ssh session hang or glitches, etc.

**Comment by simonbugler** [comment]
After a bit of testing this happens when I'm logged in via ssh and I copy/paste the one-line by triple click on a Mac. It must copy in a spurious character ...
