### ISSUE TITLE
explorerhat script on Jessie

### ISSUE THREAD

**Issue by RogueM** [pimoroni/get#2]
tested against img 20015-09-24, straight after first boot

+ pulled all dependencies
+ install competed successfully according to script
- failed to enable i2c despite claiming success

reboot did not help. I had to manually launch raspi-confi, enable i2c and reboot. Then everything seemed to work - only tried test.py using python2 and python3.

**Comment by RogueM** [comment]
I tested against Wheezy img 2015-05-05, straight after first boot

+ pulled dependencies
+ installed completed successfully according to script
+ installed completed successfully according to tests

one important note here is that the enabling of i2c was marked as success in green, with prompt a reboot would be required in red. As expected a reboot was required, but no manual fiddling with raspi-config was required!

**Comment by Gadgetoid** [comment]
Darn. This might explain the recent surge of confused Explorer HAT users.

For the record, I get my "enable i2c" logic from Raspi Config's guts. Ideally I'd love raspi-config to accept command-line arguments like: `sudo raspi-config i2c enable`, but I don't think that's ever going to happen; the display logic and functionality of raspi-config are very tightly intertwined.

**Comment by RogueM** [comment]
Hum, I feared raspi-config could be quite opaque... is launching it, directed to the appropriate screen at the end of the 'get' script technically possible maybe?

**Comment by RogueM** [comment]
been trying to get my head around your i2c script. Probing a Jessie image with a script derived from it it seems to me that the problem is that the kernelatleast function is failing... I'm looking into it but can't say I fully understand how it's supposed to work.

**Comment by RogueM** [comment]
on this image I get $kver=417+ which is then failing the comparison since it isn't an integer.

**Comment by RogueM** [comment]
I must say I'm immensely confused... by the looks of it you format kver to 4 char(expecting an int), but then call the function with a parameter 5 char long... wouldn't you always get the same result from the -ge comparison?

**Comment by RogueM** [comment]
PR filed. But like I said the kernelatleast logic seems decorative to me, I can't see it's value but I might be missing the obvious.

Still, unless you have time to look at it I would recommend pushing those 'fixes' as I believe all the Pimoroni stuff requiring either i2c or spi suffer from the same issue i.e users are required to enable those interface manually.

**Comment by Gadgetoid** [comment]
I think I might have been having one of those programming moments when I hacked up the kernel check. I felt it was necessary to make sure the scripts don't run on any untested platforms, but Raspbian doesn't change *that* much.

I'll have a look at your tweaks!

**Comment by RogueM** [comment]
My best guess is that you wanted to protect against some early Jessie distro, based on kernel version 3.18.5.0, but I think line 16 should have been 'kver=${kver:0:5}' to have any effect.

... I think it will be worth revising the code at some point, as it is (or was for that matter) the kernel check will never have any effect. Maybe keep the function in but comment it to reflect it's just there in case you need it?

**Comment by RogueM** [comment]
closing this one, if any other changes should be done this is to the i2c(spa) scripts.
