### ISSUE TITLE
Enviroplus script failed due to no login

### ISSUE THREAD

**Issue by Troubadoure** [pimoroni/get#204]
When trying to install the enviroplus-python library I was given an error saying that I was unable to connect to Github. When then installing manually using git clone it asked me for my login credentials. Going back and re-running the script then worked.

Suggest add handling to login to GitHub if username and password are required instead of just responding with a failed to connect message.

**Comment by Gadgetoid** [comment]
A straight git clone from a public repository shouldn't require login credentials at all- what's different about your git configuration?

**Comment by Troubadoure** [comment]
@Gadgetoid It was a fresh install of Raspberry pi os lite and git was installed using this script

**Comment by Gadgetoid** [comment]
That's mighty strange. Are you behind some kind of firewall or proxy that might be messing with GitHub communications?

**Comment by Troubadoure** [comment]
@Gadgetoid Nope nothing like that. The only thing it would’ve run through is PiHole (Ad blocker)
