### ISSUE TITLE
spotipy script not able to patch Mopidy config

### ISSUE THREAD

**Issue by tuxpeople** [pimoroni/get#206]
Today, I tried to install my pirate radio. 

As described [here](https://learn.pimoroni.com/tutorial/sandyj/streaming-spotify-to-your-pi), I ran this:

`curl https://get.pimoroni.com/spotipy | bash`

Unfortunately, I got some error while the script was trying to patch the mopidy.conf:

![Bildschirmfoto 2020-08-11 um 09 17 30](https://user-images.githubusercontent.com/1506076/89877789-e3c89a80-dbc0-11ea-9417-f4c661714882.png)

After applying the changes by hand, I wasn't able to access iris. Looks like it's not installed (but I thought I saw it while the script was running). Versions used:

![Bildschirmfoto 2020-08-11 um 10 03 56](https://user-images.githubusercontent.com/1506076/89877784-e1fed700-dbc0-11ea-97e0-3d6694210fa3.png)

Tested with latest raspbian (2020-02-13-raspbian-buster-lite.img

**Comment by Gadgetoid** [comment]
Thanks for rising to the challenge to fix this!
