### ISSUE TITLE
build/bdist.linux-armv6l/egg/sounddevice.py - ln 237x

### ISSUE THREAD

**Issue by vodzurk** [pimoroni/get#210]
Installing to a (almost) clean Raspian Buster Lite image, on a Pi Zero W.  Only change from base was turning wi-fi on, which made me set my country code (GB).

Screenshot attached, sorry for cutting last digit of line number, am sure somebody can figure it out.

Install continued... but hung for a couple of minutes on this error.  This long delay might worry some peep and possibly cause them to pull the plug to try again.

Edit: (Extra info) 
Started the install using the single-line installer command:
curl -sSL https://get.pimoroni.com/enviroplus | bash

![IMG_20210407_155040](https://user-images.githubusercontent.com/10724363/113888369-32fbb500-97ba-11eb-94c4-edbd4e64a64a.jpg)

**Comment by Gadgetoid** [comment]
I've dropped Python 2 support from Enviro Plus, which should fix this.
