### ISSUE TITLE
Enviro+ re-install gives errors 

### ISSUE THREAD

**Issue by peter-65** [pimoroni/get#211]
following checking for dependencies - removing files permission denied. 

/home/pi/pimoroni/enviroplus-python/libary/ and the following files :- 
dist/envorplus-0.0.5-py3.egg, 
build/lib/enviroplus/__init__.py
build/lib/enviroplus/gas.py
build/lib/enviroplus/noise.py
enviroplus.egg-info/top_level.txt
enviroplus.egg-info/sources.txt
enviroplus.egg-info/requires.txt
enviroplus.egg-info/dependency_links.txt
enviroplus.egg-info/pkg-info 

github-repo already present. updateing....
Fatal: not a git repository (or any of the parent directory) : .git

sudo ./install.sh command not found 
(red text) 
some changes made to your sgystem rtequire
your computer to reboot to trake effect. 

(back to white text)
would you like to reboot now (y/N)

<img width="782" alt="pim-err-1" src="https://user-images.githubusercontent.com/12758431/140932281-058c0bad-cacf-445d-bda6-51288ce43fa5.png">

--------------------------------------------------
had errors trying to run examples : - (will be trying to fix these by a maual install)

The following given as exaples of errors with instaaled programs and why i was re-installing the programs for enviro+
<img width="705" alt="pim-err-2" src="https://user-images.githubusercontent.com/12758431/140933487-169528c5-2031-4e26-885f-c10f70f1cd3b.png">

<img width="902" alt="pim-err-3" src="https://user-images.githubusercontent.com/12758431/140933506-a27a8482-2e8d-4636-8755-a8040a91317e.png">

<img width="877" alt="pim-err-4" src="https://user-images.githubusercontent.com/12758431/140933515-f7997c9c-65aa-4a2e-b551-4f66c4296451.png">

**Comment by peter-65** [comment]
Sorry about the spelling mistakes I'm dyslexic and had not re-checked before added to git hub.

**Comment by Gadgetoid** [comment]
Those look like connectivity errors and not an issue with the library.

What do you see if - in the command-line - you run `i2cdetect -y 1`?

**Comment by peter-65** [comment]
The problem with the enviro+ board was down to a ribbon cable not making the connection fully, once I put the board direct to a pi all examples worked.. 

 

But the problem of the one-line install on re-install is not corrected as far as I know. Will try to run it again on a full OS build and updates. 

 

I downloaded the git hut page via zip and expanded it and then ran the install.sh from that and there was no error after I had force removed all directories under the Pimoroni directory. 

 

I’m about to install it on a new sd card build and I will install from the curl /bash and then do it a second time and see if the permission error occurs again.

 

All went fine this time around, with a second load of the ‘curl’ install.

 

You can close this on git hub,

 

Peter Green
