### ISSUE TITLE
Curl usage inconsistency

### ISSUE THREAD

**Issue by lurch** [pimoroni/get#40]
In https://github.com/pimoroni/get/blob/master/README.md and also within the scripts themselves (e.g. [here](https://github.com/pimoroni/get/blob/master/installers/drumhat) or [here](https://github.com/pimoroni/get/blob/master/installers/scrollphat)), curl is invoked as `curl -sS get.pimoroni.com/some_script` but on the separate product-install instructions (e.g. [here](https://github.com/pimoroni/drum-hat/blob/master/README.md) or [here](https://github.com/pimoroni/scroll-phat/blob/master/README.md)) curl is invoked with an extra argument i.e. `curl -sSL get.pimoroni.com/some_script`.

This means when you follow the instructions and run e.g. `curl -sSL get.pimoroni.com/drumhat | bash` then it displays:
```
If you want to see what this script does before
running it, you should run:
    \curl -sS get.pimoroni.com/drumhat
```
and it seems a little confusing to have two different sets of option-flags to `curl`.
I.e. what I guess I'm asking is: should all the product-specific `README.md` files (in each of their separate github repos) be updated to remove the inconsistent `-L` flag from the `curl` command?
(I'm guessing that if the -L flag was *actually* required, then none of the installer-scripts themselves (which don't use -L) would work)

**Comment by RogueM** [comment]
yeah... sigh... updating each repo I would need to PR and @Gadgetoid to merge at this point, not likely to happen... the L is not needed indeed in the context of those scripts, at this stage anyhow.

**Comment by RogueM** [comment]
I have made some PR in the repos that used a different syntax than that used in the scripts... it might take some time before they are merged and therefore curl standardisation in effect.

**Comment by lurch** [comment]
:+1:
