### ISSUE TITLE
Skywriter HAT install script issues

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/get#64]
Copied from https://github.com/pimoroni/skywriter-hat/issues/16.

@jorisvervuurt says:

> I noticed a few issues when trying to setup the Skywriter HAT:

> When running the install script on a clean install of the latest Raspbian Jessie (Lite) image (on a Pi 3 in my case), it appears to be running fine the first time.

> 1. The install script appears to fail when trying to enable I2C.
Manually enabling I2C through `raspi-config` works.

> 2. When importing the `skywriter` Python library, a RPi.GPIO warning is shown regarding an already-in-use channel. Although this can be ignored using `GPIO.setwarnings(False)` as the library works fine, it's obviously not the best option.

> 3. When re-running the install script, it fails on trying to install `smbus`.

**Comment by RogueM** [comment]
1 - it depends how the config.txt EOF looks... the script can trip over itself if there's no final LF, yes... I believe. But that should not happen on a clean image though, AFAIK. Either way I need to look at it and make it handle that case more robustly, yes.

2. That's one of the reported and confirmed weirdness with Skywriter, yes, whether it's to do something with EEPROM or not I don't know.

3. you need to push a new lib, I corrected the setup.py in the recent PR.

**Comment by Gadgetoid** [comment]
3. I've pushed the new lib and tagged accordingly. See: https://github.com/pimoroni/skywriter-hat/commit/3379ab299b758478dfb1ff3e7a9c4c306b4ea6ce

**Comment by RogueM** [comment]
I had a check and that issue was probably raised before the i2c script was updated last, as it's rock solid in the live version I did following issues with DietPi (basically was he reported).

either way, there is a new version of all hardware scripts so if the live version is about to change.
