### ISSUE TITLE
Scripts on Jessie Lite

### ISSUE THREAD

**Issue by RogueM** [pimoroni/get#8]
Just a heads up to say the examples folders are not properly copied on Jessie Lite. I'll have a look tomorrow as my brain is too tired to do much but typing this message before it wanders into wonderland in a brief moment!

**Comment by RogueM** [comment]
right, the answer is simple: git s not installed by default, so will need adding to the requirements!

**Comment by RogueM** [comment]
It seems also that pip-3.2 is nowhere to be found in the repo, strange as that should have nothing to do with Raspbian Lite itself. I'll have to check tomorrow if that means some recent remote  changes have broken the scripts further!

**Comment by RogueM** [comment]
right, it's simply named 'pip3' now, yikes!

**Comment by RogueM** [comment]
it's version 3.4 now, in /usr/lib/python3/dist-packages
... I'll check the situation on Wheezy (early Jessie) tomorrow and modify the scripts so they work on both.

**Comment by Gadgetoid** [comment]
Zoiks. Definitely going to need some logic tomfoolerly to accommodate the new without breaking the old. Thanks for taking a look!

**Comment by RogueM** [comment]
Actually, after looking at my backups since last April my conclusion is that it is safe to replace all instances of pip-3.2 by pip3... we can go the extra mile and add the logic to fall back on pip-3.2 but I think ensuring that pip s up-to-date with 'pip install --upgrade pip' will work on any Wheezy and Jessie install.

Are you concerned about supporting anything older than Wheezy?

**Comment by RogueM** [comment]
I filed a PR to fix this now. Just the unicornhat script for the time being since I have plans to roll the pkgdeplist in all others (might as well, since git needs adding to list).

... will test it again once posted since I had to install git to clone my repo to test, removing it to verify it got pulled should be the same but you never know :D

**Comment by RogueM** [comment]
right, I need to rethink this. Basically, if python3-pip is not installed yet then it will fail, although if you then retry it will work.

I think I just need to make the check a function and then call it when needed rather than set the variable at the start of the install process. Will have a look later (when my cat is not on me!)

**Comment by RogueM** [comment]
there you go, I think it works now (famous last words)

**Comment by RogueM** [comment]
it's in control now. I just need to roll the standardised template to all scripts and they'll all be fixed in one go...
